-- Fuel-Aware Smart Inventory System — Core Database Schema
-- Run this SQL in your Supabase SQL Editor to create all required tables.
-- Timestamps use ISO 8601 / timestamptz. Units: liters and kilometers.

-- ---------------------------------------------------------------------------
-- vehicles
-- Static metadata for each tracked vehicle.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicles (
  "vehicleId"           TEXT        PRIMARY KEY,
  "plateNumber"         TEXT        NOT NULL UNIQUE,
  "label"               TEXT,
  "tankCapacityLiters"  NUMERIC,
  "assignedDriver"      TEXT,
  "status"              TEXT        NOT NULL DEFAULT 'active',
  "createdAt"           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- telemetry_raw
-- Preserves received payloads exactly as sent, for debugging and auditing.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telemetry_raw (
  "telemetryId"  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "receivedAt"   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "payload"      JSONB       NOT NULL,
  "source"       TEXT        NOT NULL
);

-- ---------------------------------------------------------------------------
-- telemetry_normalized
-- Cleaned, unit-normalized time-series records derived from telemetry_raw.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telemetry_normalized (
  "telemetryId"       UUID        PRIMARY KEY,
  "vehicleId"         TEXT        NOT NULL REFERENCES vehicles("vehicleId"),
  "deviceId"          TEXT        NOT NULL,
  "timestamp"         TIMESTAMPTZ NOT NULL,
  "fuelLevelLiters"   NUMERIC     NOT NULL,
  "fuelLevelPercent"  NUMERIC,
  "latitude"          NUMERIC     NOT NULL,
  "longitude"         NUMERIC     NOT NULL,
  "speedKph"          NUMERIC,
  "engineStatus"      TEXT
);

CREATE INDEX IF NOT EXISTS idx_telemetry_normalized_vehicle_timestamp
  ON telemetry_normalized ("vehicleId", "timestamp" DESC);

-- ---------------------------------------------------------------------------
-- vehicle_latest_state
-- Single-row-per-vehicle cache for fast UI reads.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicle_latest_state (
  "vehicleId"         TEXT        PRIMARY KEY REFERENCES vehicles("vehicleId"),
  "lastSeenAt"        TIMESTAMPTZ NOT NULL,
  "fuelLevelLiters"   NUMERIC     NOT NULL,
  "fuelLevelPercent"  NUMERIC,
  "latitude"          NUMERIC,
  "longitude"         NUMERIC,
  "engineStatus"      TEXT,
  "deviceStatus"      TEXT,
  "currentAlertLevel" TEXT
);

-- ---------------------------------------------------------------------------
-- alerts
-- Suspicious conditions and warnings generated by the rule engine.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alerts (
  "alertId"    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "vehicleId"  TEXT        NOT NULL REFERENCES vehicles("vehicleId"),
  "type"       TEXT        NOT NULL,
  "severity"   TEXT        NOT NULL,
  "status"     TEXT        NOT NULL DEFAULT 'open',
  "message"    TEXT,
  "evidence"   JSONB,
  "createdAt"  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "resolvedAt" TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_alerts_vehicle_created
  ON alerts ("vehicleId", "createdAt" DESC);

-- ---------------------------------------------------------------------------
-- trips
-- Aggregated movement sessions derived from telemetry.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trips (
  "tripId"         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  "vehicleId"      TEXT        NOT NULL REFERENCES vehicles("vehicleId"),
  "startTime"      TIMESTAMPTZ NOT NULL,
  "endTime"        TIMESTAMPTZ,
  "distanceKm"     NUMERIC,
  "fuelUsedLiters" NUMERIC,
  "avgSpeedKph"    NUMERIC
);

CREATE INDEX IF NOT EXISTS idx_trips_vehicle_start
  ON trips ("vehicleId", "startTime" DESC);
